export default [
  {
    title: 'auth',
    desc: 'A light graphql authentication server built on RedisGraph (Kubernetes ready)',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/auth',
    starred: true,
  },
  {
    title: 'rgraph',
    desc: 'A high performance Node.js RedisGraph client',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/rgraph',
    starred: true,
  },
  {
    title: 'doubt',
    desc: 'An elegant and minimal TAP 13 compliant testing library',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/doubt',
    starred: true,
  },
  {
    title: 'shimio',
    desc: 'A minimal multiplexed Websocket server and client',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/shimio',
    starred: true,
  },
  {
    title: 'disk',
    desc: 'Store and query your GraphQL types in Redis (and redisearch)',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/disk',
    starred: true,
  },
  {
    title: 'graphql-http',
    desc: 'A GraphQL http server and client using SSE',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/graphql-http',
  },
  {
    title: 'graphql-batch-executor',
    desc: 'A readable stream executing multiple graphql operations in parallel',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/graphql-batch-executor',
  },
  {
    title: 'graphql-plate',
    desc: 'An apollo-koa graphql boilerplate',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/graphql-plate',
  },
  {
    title: 'shimio-graphql',
    desc: 'A GraphQL websocket server and client built on Shimio',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/shimio-graphql',
  },
  {
    title: 'hydre.io',
    desc: 'The hydre.io website',
    lang: 'Vue.js',
    color: '#1976D2',
    link: 'https://github.com/HydreIO/hydre.io',
  },
  {
    title: 'vueplate',
    desc: 'A PWA boilerplate for the offline web',
    lang: 'Vue.JS',
    color: '#1976D2',
    link: 'https://github.com/HydreIO/vueplate',
  },
  {
    title: 'cfn',
    desc: 'Easily manage cloudformation stacks in javascript',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/cfn',
  },
  {
    title: 'disco-pod',
    desc: 'A pod discovery sidecar for Kubernetes',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/disco-pod',
  },
  {
    title: 'whooks',
    desc: 'A Taiga.io webhook server for Discord',
    lang: 'Javascript',
    color: '#FDD835',
    link: 'https://github.com/HydreIO/whooks',
  },
  {
    title: 'shimio-graphql-explorer',
    desc: 'A minimalist Graphql playground for @hydre/shimio-graphql',
    lang: 'Vue.JS',
    color: '#1976D2',
    link: 'https://github.com/usidy/shimio-graphql-explorer',
  },
  {
    title: 'sceatorio',
    desc: 'A multiplayer pve/pvp factorio mod',
    lang: 'Lua',
    color: '#43A047',
    link: 'https://github.com/Sceat/sceatorio',
  },
  {
    title: 'utxo-tool',
    desc: 'Tool to consolidate bitcoin unspent transaction (or all rpc compatible nodes)',
    lang: 'Java',
    color: '#C2185B',
    link: 'https://github.com/Sceat/utxo-tool',
  },
  {
    title: 'Wants more ?',
    desc: 'Visit my github page !',
    lang: 'Over 3500 contributions in the last year',
    color: '#8E24AA',
    link: 'https://github.com/Sceat/',
  },
]
